spring:
  datasource:
    url: jdbc:mysql://10.30.223.40:3306/qp-rebate-data?characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 7dmMEN*R2
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
  application:
    name: account-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8504
mybatis:
  type-aliases-package: com.qp.account.entity
  mapper-locations: classpath:com.qp.account.mapper/*.xml
mapper:
  mappers: com.qp.account.common.CommonMapper
  identity: MYSQL
  not-empty: false
